services:
  mongodb:
    image: mongo:7.0
    container_name: mongodb
    env_file:
      - .env
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - ai_network

  valkey:
    image: valkey/valkey:latest
    container_name: valkey
    ports:
      - "6379:6379"
    networks:
      - ai_network

networks:
  ai_network:
    driver: bridge

volumes:
  mongodb_data:
